# Generated by Django 5.0 on 2023-12-09 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('contact_detail', models.TextField(verbose_name="Vendor's contact details")),
                ('vendor_code', models.CharField(max_length=32, unique=True, verbose_name="Vendor's Code")),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's delivery rate")),
                ('quality_rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's quality rating")),
                ('average_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's average response time")),
                ('fulfillment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's fulfillment rate")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vm_vendor_profile',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's delivery rate")),
                ('quality_rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's quality rating")),
                ('average_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's average response time")),
                ('fulfillment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vendor's fulfillment rate")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_related', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_performance', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vm_vendor_performance',
            },
        ),
    ]
