# Generated by Django 5.0 on 2023-12-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's average response time", max_digits=10, verbose_name="Vendor's average response time"),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's order fulfillment rate", max_digits=10, verbose_name="Vendor's fulfillment rate"),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's on time delivery rate", max_digits=10, verbose_name="Vendor's delivery rate"),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='quality_rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's avg quality rating", max_digits=10, verbose_name="Vendor's quality rating"),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's average response time", max_digits=10, verbose_name="Vendor's average response time"),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_detail',
            field=models.TextField(help_text="Vendor's contact details", verbose_name="Vendor's contact details"),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's order fulfillment rate", max_digits=10, verbose_name="Vendor's fulfillment rate"),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text="Vendor's name.", max_length=255, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's on time delivery rate", max_digits=10, verbose_name="Vendor's delivery rate"),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's avg quality rating", max_digits=10, verbose_name="Vendor's quality rating"),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(help_text='User associated with vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(help_text="Vendor's unique code", max_length=32, unique=True, verbose_name="Vendor's Code"),
        ),
    ]
